<?php

declare(strict_types=1);

namespace CodingSunshine\Architect\Console\Commands;

use CodingSunshine\Architect\Console\Concerns\DisallowsProduction;
use CodingSunshine\Architect\Services\StateManager;
use Illuminate\Console\Command;

final class WhyCommand extends Command
{
    use DisallowsProduction;

    protected $signature = 'architect:why {path : File path (relative or absolute)}';

    protected $description = 'Report which generator produced a generated file';

    public function handle(StateManager $state): int
    {
        $exit = $this->disallowProduction();
        if ($exit !== null) {
            return $exit;
        }

        $path = (string) $this->argument('path');
        $base = base_path();
        $resolved = str_starts_with($path, '/') ? $path : $base . '/' . $path;
        $normalized = str_replace('\\', '/', $resolved);
        $relative = str_starts_with($normalized, $base) ? substr($normalized, strlen($base) + 1) : $path;

        $data = $state->load();
        $generated = $data['generated'] ?? [];

        if (! isset($generated[$relative]) && ! isset($generated[$normalized])) {
            $this->error("File is not in Architect state: {$path}");
            $this->line('Run architect:status to see tracked files.');

            return self::FAILURE;
        }

        $generator = $this->inferGenerator($relative);
        $this->info("File: {$relative}");
        $this->line("Generated by: {$generator}");
        $this->line('Source: draft (models, actions, or pages depending on generator).');

        return self::SUCCESS;
    }

    private function inferGenerator(string $path): string
    {
        if (str_contains($path, 'app/Models/')) {
            return 'model';
        }
        if (str_contains($path, 'database/migrations/')) {
            return 'migration';
        }
        if (str_contains($path, 'database/factories/')) {
            return 'factory';
        }
        if (str_contains($path, 'database/seeders/')) {
            return 'seeder';
        }
        if (str_contains($path, 'app/Actions/')) {
            return 'action';
        }
        if (str_contains($path, 'app/Http/Controllers/')) {
            return 'controller';
        }
        if (str_contains($path, 'app/Http/Requests/')) {
            return 'request';
        }
        if (str_contains($path, 'routes/')) {
            return 'route';
        }
        if (str_contains($path, 'resources/js/pages/') || str_contains($path, 'resources/views/pages/') || str_contains($path, 'resources/views/livewire/') || str_contains($path, 'app/Livewire/')) {
            return 'page';
        }
        if (str_contains($path, 'resources/js/types/')) {
            return 'typescript';
        }
        if (str_contains($path, 'tests/')) {
            return 'test';
        }

        return 'unknown';
    }
}
